defaults: &defaults
  host: localhost
  encoding: utf8
  pool: 5
  username: postgres
  password: password
  adapter: postgresql
  template: template0

development:
  <<: *defaults
  database: junkedrawer-api_development

test:
  <<: *defaults
  database: junkedrawer-api_test

production:
  <<: *defaults
  database: junkedrawer-api_production

