 City.create (name: "ABEJORRAL")
 City.create (name: "ABREGO")
 City.create (name: "ABRIAQUI")
 City.create (name: "ACACIAS")
 City.create (name: "ACANDI")
 City.create (name: "ACEVEDO")
 City.create (name: "ACHI")
 City.create (name: "AGRADO")
 City.create (name: "AGUA DE DIOS")
 City.create (name: "AGUACHICA")
 City.create (name: "AGUADA SANTANDER")
 City.create (name: "AGUADAS CALDAS")
 City.create (name: "AGUAZUL")
 City.create (name: "AGUSTIN CODAZZI")
 City.create (name: "AIPE")
 City.create (name: "ALBAN CUNDINAMARCA")
 City.create (name: "ALBAN NARINO")
 City.create (name: "ALBANIA CAQUETA")
 City.create (name: "ALBANIA LA GUAJIRA")
 City.create (name: "ALBANIA SANTANDER")
 City.create (name: "ALCALA")
 City.create (name: "ALDANA")
 City.create (name: "ALEJANDRIA")
 City.create (name: "ALGARROBO")
 City.create (name: "ALGECIRAS")
 City.create (name: "ALMAGUER")
 City.create (name: "ALMEIDA")
 City.create (name: "ALPUJARRA")
 City.create (name: "ALTAMIRA")
 City.create (name: "ALTO BAUDO")
 City.create (name: "ALTOS DEL ROSARIO")
 City.create (name: "ALVARADO")
 City.create (name: "AMAGA")
 City.create (name: "AMALFI")
 City.create (name: "AMBALEMA")
 City.create (name: "ANAPOIMA")
 City.create (name: "ANCUYA")
 City.create (name: "ANDALUCIA")
 City.create (name: "ANDES")
 City.create (name: "ANGELOPOLIS")
 City.create (name: "ANGOSTURA")
 City.create (name: "ANOLAIMA")
 City.create (name: "ANORI")
 City.create (name: "ANSERMA")
 City.create (name: "ANSERMANUEVO")
 City.create (name: "ANZA")
 City.create (name: "ANZOATEGUI")
 City.create (name: "APARTADO")
 City.create (name: "APIA")
 City.create (name: "APULO")
 City.create (name: "AQUITANIA")
 City.create (name: "ARACATACA")
 City.create (name: "ARANZAZU")
 City.create (name: "ARATOCA")
 City.create (name: "ARAUCA")
 City.create (name: "ARAUQUITA")
 City.create (name: "ARBELAEZ")
 City.create (name: "ARBOLEDA NARINO")
 City.create (name: "ARBOLEDAS SANTANDER")
 City.create (name: "ARBOLETES")
 City.create (name: "ARCABUCO")
 City.create (name: "ARENAL")
 City.create (name: "ARGELIA ANTIOQUIA")
 City.create (name: "ARGELIA CAUCA")
 City.create (name: "ARGELIA VALLE DEL CAUCA")
 City.create (name: "ARIGUANI")
 City.create (name: "ARJONA")
 City.create (name: "ARMENIA ANTIOQUIA")
 City.create (name: "ARMENIA QUINDIO")
 City.create (name: "ARMERO")
 City.create (name: "ARROYOHONDO")
 City.create (name: "ASTREA")
 City.create (name: "ATACO")
 City.create (name: "ATRATO")
 City.create (name: "AYAPEL")
 City.create (name: "BAGADO")
 City.create (name: "BAHIA SOLANO")
 City.create (name: "BAJO BAUDO")
 City.create (name: "BALBOA CAUCA")
 City.create (name: "BALBOA RISARALDA")
 City.create (name: "BARANOA")
 City.create (name: "BARAYA")
 City.create (name: "BARBACOAS")
 City.create (name: "BARBOSA ANTIOQUIA")
 City.create (name: "BARBOSA SANTANDER")
 City.create (name: "BARICHARA")
 City.create (name: "BARRANCA DE UPIA")
 City.create (name: "BARRANCABERMEJA")
 City.create (name: "BARRANCAS")
 City.create (name: "BARRANCO DE LOBA")
 City.create (name: "BARRANCO MINAS")
 City.create (name: "BARRANQUILLA")
 City.create (name: "BECERRIL")
 City.create (name: "BELALCAZAR")
 City.create (name: "BELEN BOYACA")
 City.create (name: "BELEN DE BAJIRA")
 City.create (name: "BELEN DE LOS ANDAQUIES")
 City.create (name: "BELEN DE UMBRIA")
 City.create (name: "BELEN NARINO")
 City.create (name: "BELLO")
 City.create (name: "BELMIRA")
 City.create (name: "BELTRAN")
 City.create (name: "BERBEO")
 City.create (name: "BETANIA")
 City.create (name: "BETEITIVA")
 City.create (name: "BETULIA ANTIOQUIA")
 City.create (name: "BETULIA SANTANDER")
 City.create (name: "BITUIMA")
 City.create (name: "BOAVITA")
 City.create (name: "BOCHALEMA")
 City.create (name: "BOGOTA")
 City.create (name: "BOJACA")
 City.create (name: "BOJAYA")
 City.create (name: "BOLIVAR")
 City.create (name: "BOLIVAR CAUCA")
 City.create (name: "BOLIVAR SANTANDER")
 City.create (name: "BOLIVAR VALLE DEL CAUCA")
 City.create (name: "BOSCONIA")
 City.create (name: "BOYACA")
 City.create (name: "BRICENO ANTIOQUIA")
 City.create (name: "BRICENO BOYACA")
 City.create (name: "BUCARAMANGA")
 City.create (name: "BUCARASICA")
 City.create (name: "BUENAVENTURA")
 City.create (name: "BUENAVISTA BOYACA")
 City.create (name: "BUENAVISTA CORDOBA")
 City.create (name: "BUENAVISTA QUINDIO")
 City.create (name: "BUENAVISTA SUCRE")
 City.create (name: "BUENOS AIRES")
 City.create (name: "BUESACO")
 City.create (name: "BUGALAGRANDE")
 City.create (name: "BURITICA")
 City.create (name: "BUSBANZA")
 City.create (name: "CABRERA CUNDINAMARCA")
 City.create (name: "CABRERA SANTANDER")
 City.create (name: "CABUYARO")
 City.create (name: "CACAHUAL")
 City.create (name: "CACERES")
 City.create (name: "CACHIPAY")
 City.create (name: "CACHIRA")
 City.create (name: "CACOTA")
 City.create (name: "CAICEDO")
 City.create (name: "CAICEDONIA")
 City.create (name: "CAIMITO")
 City.create (name: "CAJAMARCA")
 City.create (name: "CAJIBIO")
 City.create (name: "CAJICA")
 City.create (name: "CALAMAR BOLIVAR")
 City.create (name: "CALAMAR GUAVIARE")
 City.create (name: "CALARCA")
 City.create (name: "CALDAS ANTIOQUIA")
 City.create (name: "CALDAS BOYACA")
 City.create (name: "CALDONO")
 City.create (name: "CALI")
 City.create (name: "CALIFORNIA")
 City.create (name: "CALIMA")
 City.create (name: "CALOTO")
 City.create (name: "CAMPAMENTO")
 City.create (name: "CAMPO DE LA CRUZ")
 City.create (name: "CAMPOALEGRE")
 City.create (name: "CAMPOHERMOSO")
 City.create (name: "CANALETE")
 City.create (name: "CANASGORDAS")
 City.create (name: "CANDELARIA")
 City.create (name: "CANDELARIA VALLE DEL CAUCA")
 City.create (name: "CANTAGALLO")
 City.create (name: "CAPARRAPI")
 City.create (name: "CAPITANEJO")
 City.create (name: "CAQUEZA")
 City.create (name: "CARACOLI")
 City.create (name: "CARAMANTA")
 City.create (name: "CARCASI")
 City.create (name: "CAREPA")
 City.create (name: "CARMEN DE APICALA")
 City.create (name: "CARMEN DE CARUPA")
 City.create (name: "CARMEN DEL DARIEN")
 City.create (name: "CAROLINA")
 City.create (name: "CARTAGENA")
 City.create (name: "CARTAGENA DEL CHAIRA")
 City.create (name: "CARTAGO")
 City.create (name: "CARURU")
 City.create (name: "CASABIANCA")
 City.create (name: "CASTILLA LA NUEVA")
 City.create (name: "CAUCASIA")
 City.create (name: "CEPITA")
 City.create (name: "CERETE")
 City.create (name: "CERINZA")
 City.create (name: "CERRITO")
 City.create (name: "CERRO SAN ANTONIO")
 City.create (name: "CERTEGUI")
 City.create (name: "CHACHAGUI")
 City.create (name: "CHAGUANI")
 City.create (name: "CHALAN")
 City.create (name: "CHAMEZA")
 City.create (name: "CHAPARRAL")
 City.create (name: "CHARALA")
 City.create (name: "CHARTA")
 City.create (name: "CHIA")
 City.create (name: "CHIBOLO")
 City.create (name: "CHIGORODO")
 City.create (name: "CHIMA CORDOBA")
 City.create (name: "CHIMA SANTANDER")
 City.create (name: "CHIMICHAGUA")
 City.create (name: "CHINACOTA")
 City.create (name: "CHINAVITA")
 City.create (name: "CHINCHINA")
 City.create (name: "CHINU")
 City.create (name: "CHIPAQUE")
 City.create (name: "CHIPATA")
 City.create (name: "CHIQUINQUIRA")
 City.create (name: "CHIQUIZA")
 City.create (name: "CHIRIGUANA")
 City.create (name: "CHISCAS")
 City.create (name: "CHITA")
 City.create (name: "CHITAGA")
 City.create (name: "CHITARAQUE")
 City.create (name: "CHIVATA")
 City.create (name: "CHIVOR")
 City.create (name: "CHOACHI")
 City.create (name: "CHOCONTA")
 City.create (name: "CICUCO")
 City.create (name: "CIENAGA")
 City.create (name: "CIENAGA DE ORO")
 City.create (name: "CIENEGA")
 City.create (name: "CIMITARRA")
 City.create (name: "CIRCASIA")
 City.create (name: "CISNEROS")
 City.create (name: "CIUDAD BOLIVAR")
 City.create (name: "CLEMENCIA")
 City.create (name: "COCORNA")
 City.create (name: "COELLO")
 City.create (name: "COGUA")
 City.create (name: "COLOMBIA HUILA")
 City.create (name: "COLON NARINO")
 City.create (name: "COLON PUTUMAYO")
 City.create (name: "COLOSO")
 City.create (name: "COMBITA")
 City.create (name: "CONCEPCION ANTIOQUIA")
 City.create (name: "CONCEPCION SANTANDER")
 City.create (name: "CONCORDIA ANTIOQUIA")
 City.create (name: "CONCORDIA MAGDALENA")
 City.create (name: "CONDOTO")
 City.create (name: "CONFINES")
 City.create (name: "CONSACA")
 City.create (name: "CONTADERO")
 City.create (name: "CONTRATACION")
 City.create (name: "CONVENCION")
 City.create (name: "COPACABANA")
 City.create (name: "COPER")
 City.create (name: "CORDOBA BOLIVAR")
 City.create (name: "CORDOBA NARI�O")
 City.create (name: "CORDOBA QUINDIO")
 City.create (name: "CORINTO")
 City.create (name: "COROMORO")
 City.create (name: "COROZAL")
 City.create (name: "CORRALES")
 City.create (name: "COTA")
 City.create (name: "COTORRA")
 City.create (name: "COVARACHIA")
 City.create (name: "COVENAS")
 City.create (name: "COYAIMA")
 City.create (name: "CRAVO NORTE")
 City.create (name: "CUASPUD")
 City.create (name: "CUBARA")
 City.create (name: "CUBARRAL")
 City.create (name: "CUCAITA")
 City.create (name: "CUCUNUBA")
 City.create (name: "CUCUTA")
 City.create (name: "CUCUTILLA")
 City.create (name: "CUITIVA")
 City.create (name: "CUMARAL")
 City.create (name: "CUMARIBO")
 City.create (name: "CUMBAL")
 City.create (name: "CUMBITARA")
 City.create (name: "CUNDAY")
 City.create (name: "CURILLO")
 City.create (name: "CURITI")
 City.create (name: "CURUMANI")
 City.create (name: "DABEIBA")
 City.create (name: "DAGUA")
 City.create (name: "DIBULLA")
 City.create (name: "DISTRACCION")
 City.create (name: "DOLORES")
 City.create (name: "DON MATIAS")
 City.create (name: "DOSQUEBRADAS")
 City.create (name: "DUITAMA")
 City.create (name: "DURANIA")
 City.create (name: "EBEJICO")
 City.create (name: "EL AGUILA")
 City.create (name: "EL BAGRE")
 City.create (name: "EL BANCO")
 City.create (name: "EL CAIRO")
 City.create (name: "EL CALVARIO")
 City.create (name: "EL CANTON DEL SAN PABLO")
 City.create (name: "EL CARMEN DE ATRATO")
 City.create (name: "EL CARMEN DE BOLIVAR")
 City.create (name: "EL CARMEN DE CHUCURI")
 City.create (name: "EL CARMEN DE VIBORAL")
 City.create (name: "EL CARMEN NTE SANTANDER")
 City.create (name: "EL CASTILLO")
 City.create (name: "EL CERRITO")
 City.create (name: "EL CHARCO")
 City.create (name: "EL COCUY")
 City.create (name: "EL COLEGIO")
 City.create (name: "EL COPEY")
 City.create (name: "EL DONCELLO")
 City.create (name: "EL DORADO")
 City.create (name: "EL DOVIO")
 City.create (name: "EL ENCANTO")
 City.create (name: "EL ESPINO")
 City.create (name: "EL GUACAMAYO")
 City.create (name: "EL GUAMO")
 City.create (name: "EL LITORAL DEL SAN JUAN")
 City.create (name: "EL MOLINO")
 City.create (name: "EL PASO")
 City.create (name: "EL PAUJIL")
 City.create (name: "EL PENOL")
 City.create (name: "EL PENON BOLIVAR")
 City.create (name: "EL PENON CUNDINAMARCA")
 City.create (name: "EL PENON SANTANDER")
 City.create (name: "EL PINON")
 City.create (name: "EL PLAYON")
 City.create (name: "EL RETEN")
 City.create (name: "EL RETORNO")
 City.create (name: "EL ROBLE")
 City.create (name: "EL ROSAL")
 City.create (name: "EL ROSARIO")
 City.create (name: "EL SANTUARIO")
 City.create (name: "EL TABLON DE GOMEZ")
 City.create (name: "EL TAMBO CAUCA")
 City.create (name: "EL TAMBO NARINO")
 City.create (name: "EL TARRA")
 City.create (name: "EL ZULIA")
 City.create (name: "ELIAS")
 City.create (name: "ENCINO")
 City.create (name: "ENCISO")
 City.create (name: "ENTRERRIOS")
 City.create (name: "ENVIGADO")
 City.create (name: "ESPINAL")
 City.create (name: "FACATATIVA")
 City.create (name: "FALAN")
 City.create (name: "FILADELFIA")
 City.create (name: "FILANDIA")
 City.create (name: "FIRAVITOBA")
 City.create (name: "FLANDES")
 City.create (name: "FLORENCIA CAQUETA")
 City.create (name: "FLORENCIA CAUCA")
 City.create (name: "FLORESTA")
 City.create (name: "FLORIAN")
 City.create (name: "FLORIDA")
 City.create (name: "FLORIDABLANCA")
 City.create (name: "FOMEQUE")
 City.create (name: "FONSECA")
 City.create (name: "FORTUL")
 City.create (name: "FOSCA")
 City.create (name: "FRANCISCO PIZARRO")
 City.create (name: "FREDONIA")
 City.create (name: "FRESNO")
 City.create (name: "FRONTINO")
 City.create (name: "FUENTE DE ORO")
 City.create (name: "FUNDACION")
 City.create (name: "FUNES")
 City.create (name: "FUNZA")
 City.create (name: "FUQUENE")
 City.create (name: "FUSAGASUGA")
 City.create (name: "GACHALA")
 City.create (name: "GACHANCIPA")
 City.create (name: "GACHANTIVA")
 City.create (name: "GACHETA")
 City.create (name: "GALAN")
 City.create (name: "GALAPA")
 City.create (name: "GALERAS")
 City.create (name: "GALERAZAMBA")
 City.create (name: "GAMA")
 City.create (name: "GAMARRA")
 City.create (name: "GAMBITA")
 City.create (name: "GAMEZA")
 City.create (name: "GARAGOA")
 City.create (name: "GARZON")
 City.create (name: "GENOVA")
 City.create (name: "GIGANTE")
 City.create (name: "GINEBRA")
 City.create (name: "GIRALDO")
 City.create (name: "GIRARDOT")
 City.create (name: "GIRARDOTA")
 City.create (name: "GIRON")
 City.create (name: "GOMEZ PLATA")
 City.create (name: "GONZALEZ")
 City.create (name: "GRAMALOTE")
 City.create (name: "GRANADA ANTIOQUIA")
 City.create (name: "GRANADA CUNDINAMARCA")
 City.create (name: "GRANADA META")
 City.create (name: "GUACA")
 City.create (name: "GUACAMAYAS")
 City.create (name: "GUACARI")
 City.create (name: "GUACHETA")
 City.create (name: "GUACHUCAL")
 City.create (name: "GUADALAJARA DE BUGA")
 City.create (name: "GUADALUPE ANTIOQUIA")
 City.create (name: "GUADALUPE HUILA")
 City.create (name: "GUADALUPE SANTANDER")
 City.create (name: "GUADUAS")
 City.create (name: "GUAITARILLA")
 City.create (name: "GUAJIRA")
 City.create (name: "GUALMATAN")
 City.create (name: "GUAMAL MAGDALENA")
 City.create (name: "GUAMAL META")
 City.create (name: "GUAMO")
 City.create (name: "GUAPI")
 City.create (name: "GUAPOTA")
 City.create (name: "GUARANDA")
 City.create (name: "GUARNE")
 City.create (name: "GUASCA")
 City.create (name: "GUATAPE")
 City.create (name: "GUATAQUI")
 City.create (name: "GUATAVITA")
 City.create (name: "GUATEQUE")
 City.create (name: "GUATICA")
 City.create (name: "GUAVATA")
 City.create (name: "GUAYABAL DE SIQUIMA")
 City.create (name: "GUAYABETAL")
 City.create (name: "GUAYATA")
 City.create (name: "GUEPSA")
 City.create (name: "GUICAN")
 City.create (name: "GUTIERREZ")
 City.create (name: "HACARI")
 City.create (name: "HATILLO DE LOBA")
 City.create (name: "HATO")
 City.create (name: "HATO COROZAL")
 City.create (name: "HATONUEVO")
 City.create (name: "HELICONIA")
 City.create (name: "HERRAN")
 City.create (name: "HERVEO")
 City.create (name: "HISPANIA")
 City.create (name: "HOBO")
 City.create (name: "HONDA")
 City.create (name: "IBAGUE")
 City.create (name: "ICONONZO")
 City.create (name: "ILES")
 City.create (name: "IMUES")
 City.create (name: "INIRIDA")
 City.create (name: "INZA")
 City.create (name: "IPIALES")
 City.create (name: "IQUIRA")
 City.create (name: "ISNOS")
 City.create (name: "ISTMINA")
 City.create (name: "ITAGUI")
 City.create (name: "ITUANGO")
 City.create (name: "IZA")
 City.create (name: "JAMBALO")
 City.create (name: "JAMUNDI")
 City.create (name: "JARDIN")
 City.create (name: "JENESANO")
 City.create (name: "JERICO ANTIOQUIA")
 City.create (name: "JERICO BOYACA")
 City.create (name: "JERUSALEN")
 City.create (name: "JESUS MARIA")
 City.create (name: "JORDAN")
 City.create (name: "JUAN DE ACOSTA")
 City.create (name: "JUNIN")
 City.create (name: "JURADO")
 City.create (name: "LA APARTADA")
 City.create (name: "LA ARGENTINA")
 City.create (name: "LA BELLEZA")
 City.create (name: "LA CALERA")
 City.create (name: "LA CAPILLA")
 City.create (name: "LA CEJA")
 City.create (name: "LA CELIA")
 City.create (name: "LA CHORRERA")
 City.create (name: "LA CRUZ")
 City.create (name: "LA CUMBRE")
 City.create (name: "LA DORADA")
 City.create (name: "LA ESPERANZA")
 City.create (name: "LA ESTRELLA")
 City.create (name: "LA FLORIDA")
 City.create (name: "LA GLORIA")
 City.create (name: "LA GUADALUPE")
 City.create (name: "LA JAGUA DE IBIRICO")
 City.create (name: "LA JAGUA DEL PILAR")
 City.create (name: "LA LLANADA")
 City.create (name: "LA MACARENA")
 City.create (name: "LA MERCED")
 City.create (name: "LA MESA")
 City.create (name: "LA MONTANITA")
 City.create (name: "LA PALMA")
 City.create (name: "LA PAZ CESAR")
 City.create (name: "LA PAZ SANTANDER")
 City.create (name: "LA PEDRERA")
 City.create (name: "LA PENA")
 City.create (name: "LA PINTADA")
 City.create (name: "LA PLATA")
 City.create (name: "LA PLAYA")
 City.create (name: "LA PRIMAVERA")
 City.create (name: "LA SALINA")
 City.create (name: "LA SIERRA")
 City.create (name: "LA TEBAIDA")
 City.create (name: "LA TOLA")
 City.create (name: "LA UNION")
 City.create (name: "LA UNION ANTIOQUIA")
 City.create (name: "LA UNION NARINO")
 City.create (name: "LA UNION SUCRE")
 City.create (name: "LA UVITA")
 City.create (name: "LA VEGA CAUCA")
 City.create (name: "LA VEGA CUNDINAMARCA")
 City.create (name: "LA VICTORIA AMAZONAS")
 City.create (name: "LA VICTORIA BOYACA")
 City.create (name: "LA VICTORIA VALLE DEL CAUCA")
 City.create (name: "LA VIRGINIA")
 City.create (name: "LABATECA")
 City.create (name: "LABRANZAGRANDE")
 City.create (name: "LANDAZURI")
 City.create (name: "LEBRIJA")
 City.create (name: "LEGUIZAMO")
 City.create (name: "LEIVA")
 City.create (name: "LEJANIAS")
 City.create (name: "LENGUAZAQUE")
 City.create (name: "LERIDA")
 City.create (name: "LETICIA")
 City.create (name: "LIBANO")
 City.create (name: "LIBORINA")
 City.create (name: "LINARES")
 City.create (name: "LLORO")
 City.create (name: "LOPEZ")
 City.create (name: "LORICA")
 City.create (name: "LOS ANDES")
 City.create (name: "LOS CORDOBAS")
 City.create (name: "LOS PALMITOS")
 City.create (name: "LOS PATIOS")
 City.create (name: "LOS SANTOS")
 City.create (name: "LOURDES")
 City.create (name: "LURUACO")
 City.create (name: "MACANAL")
 City.create (name: "MACARAVITA")
 City.create (name: "MACEO")
 City.create (name: "MACHETA")
 City.create (name: "MADRID")
 City.create (name: "MAGANGUE")
 City.create (name: "MAGUI")
 City.create (name: "MAHATES")
 City.create (name: "MAICAO")
 City.create (name: "MAJAGUAL")
 City.create (name: "MALAGA")
 City.create (name: "MALAMBO")
 City.create (name: "MALLAMA")
 City.create (name: "MANATI")
 City.create (name: "MANAURE CESAR")
 City.create (name: "MANAURE LA GUAJIRA")
 City.create (name: "MANI")
 City.create (name: "MANIZALES")
 City.create (name: "MANTA")
 City.create (name: "MANZANARES")
 City.create (name: "MAPIRIPAN")
 City.create (name: "MAPIRIPANA")
 City.create (name: "MARGARITA")
 City.create (name: "MARIA LA BAJA")
 City.create (name: "MARINILLA")
 City.create (name: "MARIPI")
 City.create (name: "MARIQUITA")
 City.create (name: "MARMATO")
 City.create (name: "MARQUETALIA")
 City.create (name: "MARSELLA")
 City.create (name: "MARULANDA")
 City.create (name: "MATANZA")
 City.create (name: "MEDELLIN")
 City.create (name: "MEDINA")
 City.create (name: "MEDIO ATRATO")
 City.create (name: "MEDIO BAUDO")
 City.create (name: "MEDIO SAN JUAN")
 City.create (name: "MELGAR")
 City.create (name: "MERCADERES")
 City.create (name: "MESETAS")
 City.create (name: "MILAN")
 City.create (name: "MIRAFLORES BOYACA")
 City.create (name: "MIRAFLORES GUAVIARE")
 City.create (name: "MIRANDA")
 City.create (name: "MIRITI - PARANA")
 City.create (name: "MISTRATO")
 City.create (name: "MITU")
 City.create (name: "MOCOA")
 City.create (name: "MOGOTES")
 City.create (name: "MOLAGAVITA")
 City.create (name: "MOMIL")
 City.create (name: "MOMPOS")
 City.create (name: "MONGUA")
 City.create (name: "MONGUI")
 City.create (name: "MONIQUIRA")
 City.create (name: "MONITOS")
 City.create (name: "MONTEBELLO")
 City.create (name: "MONTECRISTO")
 City.create (name: "MONTELIBANO")
 City.create (name: "MONTENEGRO")
 City.create (name: "MONTERIA")
 City.create (name: "MONTERREY")
 City.create (name: "MORALES BOLIVAR")
 City.create (name: "MORALES CAUCA")
 City.create (name: "MORELIA")
 City.create (name: "MORICHAL")
 City.create (name: "MORROA")
 City.create (name: "MOSQUERA CUNDINAMARCA")
 City.create (name: "MOSQUERA NARINO")
 City.create (name: "MOTAVITA")
 City.create (name: "MURILLO")
 City.create (name: "MURINDO")
 City.create (name: "MUTATA")
 City.create (name: "MUTISCUA")
 City.create (name: "MUZO")
 City.create (name: "NARINO ANTIOQUIA")
 City.create (name: "NARINO CUNDINAMARCA")
 City.create (name: "NARINO NARINO")
 City.create (name: "NATAGA")
 City.create (name: "NATAGAIMA")
 City.create (name: "NECHI")
 City.create (name: "NECOCLI")
 City.create (name: "NEIRA")
 City.create (name: "NEIVA")
 City.create (name: "NEMOCON")
 City.create (name: "NILO")
 City.create (name: "NIMAIMA")
 City.create (name: "NOBSA")
 City.create (name: "NOCAIMA")
 City.create (name: "NORCASIA")
 City.create (name: "NOVITA")
 City.create (name: "NUEVA GRANADA")
 City.create (name: "NUEVO COLON")
 City.create (name: "NUNCHIA")
 City.create (name: "NUQUI")
 City.create (name: "OBANDO")
 City.create (name: "OCAMONTE")
 City.create (name: "OCANA")
 City.create (name: "OIBA")
 City.create (name: "OICATA")
 City.create (name: "OLAYA")
 City.create (name: "OLAYA HERRERA")
 City.create (name: "ONZAGA")
 City.create (name: "OPORAPA")
 City.create (name: "ORITO")
 City.create (name: "OROCUE")
 City.create (name: "ORTEGA")
 City.create (name: "OSPINA")
 City.create (name: "OTANCHE")
 City.create (name: "OVEJAS")
 City.create (name: "PACHAVITA")
 City.create (name: "PACHO")
 City.create (name: "PACOA")
 City.create (name: "PACORA")
 City.create (name: "PADILLA")
 City.create (name: "PAEZ")
 City.create (name: "PAICOL")
 City.create (name: "PAILITAS")
 City.create (name: "PAIME")
 City.create (name: "PAIPA")
 City.create (name: "PAJARITO")
 City.create (name: "PALERMO")
 City.create (name: "PALESTINA")
 City.create (name: "PALMAR")
 City.create (name: "PALMAR DE VARELA")
 City.create (name: "PALMAS DEL SOCORRO")
 City.create (name: "PALMIRA")
 City.create (name: "PALMITO")
 City.create (name: "PALOCABILDO")
 City.create (name: "PAMPLONA")
 City.create (name: "PAMPLONITA")
 City.create (name: "PANA PANA")
 City.create (name: "PANDI")
 City.create (name: "PANQUEBA")
 City.create (name: "PAPUNAUA")
 City.create (name: "PARAMO")
 City.create (name: "PARATEBUENO")
 City.create (name: "PASCA")
 City.create (name: "PASTO")
 City.create (name: "PATIA")
 City.create (name: "PAUNA")
 City.create (name: "PAYA")
 City.create (name: "PAZ DE ARIPORO")
 City.create (name: "PAZ DE RIO")
 City.create (name: "PEDRAZA")
 City.create (name: "PELAYA")
 City.create (name: "PENOL")
 City.create (name: "PENSILVANIA")
 City.create (name: "PEQUE")
 City.create (name: "PEREIRA")
 City.create (name: "PESCA")
 City.create (name: "PIAMONTE")
 City.create (name: "PIEDECUESTA")
 City.create (name: "PIEDRAS")
 City.create (name: "PIENDAMO")
 City.create (name: "PIJAO")
 City.create (name: "PIJINO DEL CARMEN")
 City.create (name: "PINCHOTE")
 City.create (name: "PINILLOS")
 City.create (name: "PIOJO")
 City.create (name: "PISBA")
 City.create (name: "PITAL")
 City.create (name: "PITALITO")
 City.create (name: "PIVIJAY")
 City.create (name: "PLANADAS")
 City.create (name: "PLANETA RICA")
 City.create (name: "PLATO")
 City.create (name: "POLICARPA")
 City.create (name: "POLONUEVO")
 City.create (name: "PONEDERA")
 City.create (name: "POPAYAN")
 City.create (name: "PORE")
 City.create (name: "POTOSI")
 City.create (name: "PRADERA")
 City.create (name: "PRADO")
 City.create (name: "PROVIDENCIA")
 City.create (name: "PUEBLO BELLO")
 City.create (name: "PUEBLO NUEVO")
 City.create (name: "PUEBLO RICO RISARALDA")
 City.create (name: "PUEBLORRICO")
 City.create (name: "PUEBLOVIEJO")
 City.create (name: "PUENTE NACIONAL")
 City.create (name: "PUERRES")
 City.create (name: "PUERTO ALEGRIA")
 City.create (name: "PUERTO ARICA")
 City.create (name: "PUERTO ASIS")
 City.create (name: "PUERTO BERRIO")
 City.create (name: "PUERTO BOYACA")
 City.create (name: "PUERTO CAICEDO")
 City.create (name: "PUERTO CARRENO")
 City.create (name: "PUERTO COLOMBIA")
 City.create (name: "PUERTO CONCORDIA")
 City.create (name: "PUERTO ESCONDIDO")
 City.create (name: "PUERTO GAITAN")
 City.create (name: "PUERTO GUZMAN")
 City.create (name: "PUERTO LIBERTADOR")
 City.create (name: "PUERTO LLERAS")
 City.create (name: "PUERTO LOPEZ")
 City.create (name: "PUERTO NARE")
 City.create (name: "PUERTO NARINO")
 City.create (name: "PUERTO PARRA")
 City.create (name: "PUERTO RICO")
 City.create (name: "PUERTO RONDON")
 City.create (name: "PUERTO SALGAR")
 City.create (name: "PUERTO SANTANDER AMAZONAS")
 City.create (name: "PUERTO SANTANDER NTE SANTANDER")
 City.create (name: "PUERTO TEJADA")
 City.create (name: "PUERTO TRIUNFO")
 City.create (name: "PUERTO WILCHES")
 City.create (name: "PULI")
 City.create (name: "PUPIALES")
 City.create (name: "PURACE")
 City.create (name: "PURIFICACION")
 City.create (name: "PURISIMA")
 City.create (name: "QUEBRADANEGRA")
 City.create (name: "QUETAME")
 City.create (name: "QUIBDO")
 City.create (name: "QUIMBAYA")
 City.create (name: "QUINCHIA")
 City.create (name: "QUIPAMA")
 City.create (name: "QUIPILE")
 City.create (name: "RAGONVALIA")
 City.create (name: "RAMIRIQUI")
 City.create (name: "RAQUIRA")
 City.create (name: "RECETOR")
 City.create (name: "REGIDOR")
 City.create (name: "REMEDIOS")
 City.create (name: "REMOLINO")
 City.create (name: "REPELON")
 City.create (name: "RESTREPO META")
 City.create (name: "RESTREPO VALLE DEL CAUCA")
 City.create (name: "RETIRO")
 City.create (name: "RICAURTE CUNDINAMARCA")
 City.create (name: "RICAURTE NARINO")
 City.create (name: "RIO DE ORO")
 City.create (name: "RIO IRO")
 City.create (name: "RIO QUITO")
 City.create (name: "RIO VIEJO")
 City.create (name: "RIOBLANCO")
 City.create (name: "RIOFRIO")
 City.create (name: "RIOHACHA")
 City.create (name: "RIONEGRO ANTIOQUIA")
 City.create (name: "RIONEGRO SANTANDER")
 City.create (name: "RIOSUCIO CALDAS")
 City.create (name: "RIOSUCIO CHOCO")
 City.create (name: "RISARALDA")
 City.create (name: "RIVERA")
 City.create (name: "ROBERTO PAYAN")
 City.create (name: "ROLDANILLO")
 City.create (name: "RONCESVALLES")
 City.create (name: "RONDON")
 City.create (name: "ROSAS")
 City.create (name: "ROVIRA")
 City.create (name: "SABANA DE TORRES")
 City.create (name: "SABANAGRANDE")
 City.create (name: "SABANALARGA")
 City.create (name: "SABANALARGA ATLANTICO")
 City.create (name: "SABANALARGA CASANARE")
 City.create (name: "SABANAS DE SAN ANGEL")
 City.create (name: "SABANETA")
 City.create (name: "SABOYA")
 City.create (name: "SACAMA")
 City.create (name: "SACHICA")
 City.create (name: "SAHAGUN")
 City.create (name: "SALADOBLANCO")
 City.create (name: "SALAMINA CALDAS")
 City.create (name: "SALAMINA MAGDALENA")
 City.create (name: "SALAZAR")
 City.create (name: "SALDANA")
 City.create (name: "SALENTO")
 City.create (name: "SALGAR")
 City.create (name: "SAMACA")
 City.create (name: "SAMANA")
 City.create (name: "SAMANIEGO")
 City.create (name: "SAMPUES")
 City.create (name: "SAN AGUSTIN")
 City.create (name: "SAN ALBERTO")
 City.create (name: "SAN ANDRES ANTIOQUIA")
 City.create (name: "SAN ANDRES ARCHIPIELAGO")
 City.create (name: "SAN ANDRES SANTANDER")
 City.create (name: "SAN ANDRES SOTAVENTO")
 City.create (name: "SAN ANTERO")
 City.create (name: "SAN ANTONIO")
 City.create (name: "SAN ANTONIO DEL TEQUENDAMA")
 City.create (name: "SAN BENITO")
 City.create (name: "SAN BENITO ABAD")
 City.create (name: "SAN BERNARDO CUNDINAMARCA")
 City.create (name: "SAN BERNARDO DEL VIENTO")
 City.create (name: "SAN BERNARDO NARINO")
 City.create (name: "SAN CALIXTO")
 City.create (name: "SAN CARLOS ANTIOQUIA")
 City.create (name: "SAN CARLOS CORDOBA")
 City.create (name: "SAN CARLOS DE GUAROA")
 City.create (name: "SAN CAYETANO CUNDINAMARCA")
 City.create (name: "SAN CAYETANO NTE SANTANDER")
 City.create (name: "SAN CRISTOBAL")
 City.create (name: "SAN DIEGO")
 City.create (name: "SAN EDUARDO")
 City.create (name: "SAN ESTANISLAO")
 City.create (name: "SAN FELIPE")
 City.create (name: "SAN FERNANDO")
 City.create (name: "SAN FRANCISCO ANTIOQUIA")
 City.create (name: "SAN FRANCISCO CUNDINAMARCA")
 City.create (name: "SAN FRANCISCO PUTUMAYO")
 City.create (name: "SAN GIL")
 City.create (name: "SAN JACINTO")
 City.create (name: "SAN JACINTO DEL CAUCA")
 City.create (name: "SAN JERONIMO")
 City.create (name: "SAN JOAQUIN")
 City.create (name: "SAN JOSE")
 City.create (name: "SAN JOSE DE LA MONTANA")
 City.create (name: "SAN JOSE DE MIRANDA")
 City.create (name: "SAN JOSE DE PARE")
 City.create (name: "SAN JOSE DEL FRAGUA")
 City.create (name: "SAN JOSE DEL GUAVIARE")
 City.create (name: "SAN JOSE DEL PALMAR")
 City.create (name: "SAN JUAN DE ARAMA")
 City.create (name: "SAN JUAN DE BETULIA")
 City.create (name: "SAN JUAN DE RIO SECO")
 City.create (name: "SAN JUAN DE URABA")
 City.create (name: "SAN JUAN DEL CESAR")
 City.create (name: "SAN JUAN NEPOMUCENO")
 City.create (name: "SAN JUANITO")
 City.create (name: "SAN LORENZO")
 City.create (name: "SAN LUIS ANTIOQUIA")
 City.create (name: "SAN LUIS DE GACENO")
 City.create (name: "SAN LUIS DE PALENQUE")
 City.create (name: "SAN LUIS TOLIMA")
 City.create (name: "SAN MARCOS")
 City.create (name: "SAN MARTIN CESAR")
 City.create (name: "SAN MARTIN DE LOBA")
 City.create (name: "SAN MARTIN META")
 City.create (name: "SAN MATEO")
 City.create (name: "SAN MIGUEL DE SEMA")
 City.create (name: "SAN MIGUEL PUTUMAYO")
 City.create (name: "SAN MIGUEL SANTANDER")
 City.create (name: "SAN ONOFRE")
 City.create (name: "SAN PABLO BOLIVAR")
 City.create (name: "SAN PABLO DE BORBUR")
 City.create (name: "SAN PABLO NARINO")
 City.create (name: "SAN PEDRO ANTIOQUIA")
 City.create (name: "SAN PEDRO DE CARTAGO")
 City.create (name: "SAN PEDRO DE URABA")
 City.create (name: "SAN PEDRO SUCRE")
 City.create (name: "SAN PEDRO VALLE DEL CAUCA")
 City.create (name: "SAN PELAYO")
 City.create (name: "SAN RAFAEL")
 City.create (name: "SAN ROQUE")
 City.create (name: "SAN SEBASTIAN")
 City.create (name: "SAN SEBASTIAN DE BUENAVISTA")
 City.create (name: "SAN VICENTE")
 City.create (name: "SAN VICENTE DE CHUCURI")
 City.create (name: "SAN VICENTE DEL CAGUAN")
 City.create (name: "SAN ZENON")
 City.create (name: "SANDONA")
 City.create (name: "SANTA ANA")
 City.create (name: "SANTA BARBARA ANTIOQUIA")
 City.create (name: "SANTA BARBARA DE PINTO")
 City.create (name: "SANTA BARBARA NARI�O")
 City.create (name: "SANTA BARBARA SANTANDER")
 City.create (name: "SANTA CATALINA")
 City.create (name: "SANTA HELENA DEL OPON")
 City.create (name: "SANTA ISABEL")
 City.create (name: "SANTA LUCIA")
 City.create (name: "SANTA MARIA BOYACA")
 City.create (name: "SANTA MARIA HUILA")
 City.create (name: "SANTA MARTA MAGDALENA")
 City.create (name: "SANTA ROSA BOLIVAR")
 City.create (name: "SANTA ROSA CAUCA")
 City.create (name: "SANTA ROSA DE CABAL")
 City.create (name: "SANTA ROSA DE OSOS")
 City.create (name: "SANTA ROSA DE VITERBO")
 City.create (name: "SANTA ROSA DEL SUR")
 City.create (name: "SANTA ROSALIA")
 City.create (name: "SANTA SOFIA")
 City.create (name: "SANTACRUZ")
 City.create (name: "SANTAFE DE ANTIOQUIA")
 City.create (name: "SANTANA")
 City.create (name: "SANTANDER DE QUILICHAO")
 City.create (name: "SANTIAGO DE TOLU")
 City.create (name: "SANTIAGO NTE SANTANDER")
 City.create (name: "SANTIAGO PUTUMAYO")
 City.create (name: "SANTO DOMINGO")
 City.create (name: "SANTO TOMAS")
 City.create (name: "SANTUARIO")
 City.create (name: "SAPUYES")
 City.create (name: "SARAVENA")
 City.create (name: "SARDINATA")
 City.create (name: "SASAIMA")
 City.create (name: "SATIVANORTE")
 City.create (name: "SATIVASUR")
 City.create (name: "SEGOVIA")
 City.create (name: "SESQUILE")
 City.create (name: "SEVILLA")
 City.create (name: "SIACHOQUE")
 City.create (name: "SIBATE")
 City.create (name: "SIBUNDOY")
 City.create (name: "SILOS")
 City.create (name: "SILVANIA")
 City.create (name: "SILVIA")
 City.create (name: "SIMACOTA")
 City.create (name: "SIMIJACA")
 City.create (name: "SIMITI")
 City.create (name: "SINCE")
 City.create (name: "SINCELEJO")
 City.create (name: "SIPI")
 City.create (name: "SITIONUEVO")
 City.create (name: "SOACHA")
 City.create (name: "SOATA")
 City.create (name: "SOCHA")
 City.create (name: "SOCORRO")
 City.create (name: "SOCOTA")
 City.create (name: "SOGAMOSO")
 City.create (name: "SOLANO")
 City.create (name: "SOLEDAD")
 City.create (name: "SOLITA")
 City.create (name: "SOMONDOCO")
 City.create (name: "SONSON")
 City.create (name: "SOPETRAN")
 City.create (name: "SOPLAVIENTO")
 City.create (name: "SOPO")
 City.create (name: "SORA")
 City.create (name: "SORACA")
 City.create (name: "SOTAQUIRA")
 City.create (name: "SOTARA")
 City.create (name: "SUAITA")
 City.create (name: "SUAN")
 City.create (name: "SUAREZ CAUCA")
 City.create (name: "SUAREZ TOLIMA")
 City.create (name: "SUAZA")
 City.create (name: "SUBACHOQUE")
 City.create (name: "SUCRE CAUCA")
 City.create (name: "SUCRE SANTANDER")
 City.create (name: "SUCRE SUCRE")
 City.create (name: "SUESCA")
 City.create (name: "SUPATA")
 City.create (name: "SUPIA")
 City.create (name: "SURATA")
 City.create (name: "SUSA")
 City.create (name: "SUSACON")
 City.create (name: "SUTAMARCHAN")
 City.create (name: "SUTATAUSA")
 City.create (name: "SUTATENZA")
 City.create (name: "TABIO")
 City.create (name: "TADO")
 City.create (name: "TALAIGUA NUEVO")
 City.create (name: "TAMALAMEQUE")
 City.create (name: "TAMARA")
 City.create (name: "TAME")
 City.create (name: "TAMESIS")
 City.create (name: "TAMINANGO")
 City.create (name: "TANGUA")
 City.create (name: "TARAIRA")
 City.create (name: "TARAPACA")
 City.create (name: "TARAZA")
 City.create (name: "TARQUI")
 City.create (name: "TARSO")
 City.create (name: "TASCO")
 City.create (name: "TAURAMENA")
 City.create (name: "TAUSA")
 City.create (name: "TELLO")
 City.create (name: "TENA")
 City.create (name: "TENERIFE")
 City.create (name: "TENJO")
 City.create (name: "TENZA")
 City.create (name: "TEORAMA")
 City.create (name: "TERUEL")
 City.create (name: "TESALIA")
 City.create (name: "TIBACUY")
 City.create (name: "TIBANA")
 City.create (name: "TIBASOSA")
 City.create (name: "TIBIRITA")
 City.create (name: "TIBU")
 City.create (name: "TIERRALTA")
 City.create (name: "TIMANA")
 City.create (name: "TIMBIO")
 City.create (name: "TIMBIQUI")
 City.create (name: "TINJACA")
 City.create (name: "TIPACOQUE")
 City.create (name: "TIQUISIO")
 City.create (name: "TITIRIBI")
 City.create (name: "TOCA")
 City.create (name: "TOCAIMA")
 City.create (name: "TOCANCIPA")
 City.create (name: "TOGUI")
 City.create (name: "TOLEDO ANTIOQUIA")
 City.create (name: "TOLEDO NTE SANTANDER")
 City.create (name: "TOLU")
 City.create (name: "TOLU VIEJO")
 City.create (name: "TONA")
 City.create (name: "TOPAGA")
 City.create (name: "TOPAIPI")
 City.create (name: "TORIBIO")
 City.create (name: "TORO")
 City.create (name: "TOTA")
 City.create (name: "TOTORO")
 City.create (name: "TRINIDAD")
 City.create (name: "TRUJILLO")
 City.create (name: "TUBARA")
 City.create (name: "TULUA")
 City.create (name: "TUMACO")
 City.create (name: "TUNJA")
 City.create (name: "TUNUNGUA")
 City.create (name: "TUQUERRES")
 City.create (name: "TURBACO")
 City.create (name: "TURBANA")
 City.create (name: "TURBO")
 City.create (name: "TURMEQUE")
 City.create (name: "TUTA")
 City.create (name: "TUTAZA")
 City.create (name: "UBALA")
 City.create (name: "UBAQUE")
 City.create (name: "ULLOA")
 City.create (name: "UMBITA")
 City.create (name: "UNE")
 City.create (name: "UNGUIA")
 City.create (name: "UNION PANAMERICANA")
 City.create (name: "URAMITA")
 City.create (name: "URIBE")
 City.create (name: "URIBIA")
 City.create (name: "URRAO")
 City.create (name: "URUMITA")
 City.create (name: "USIACURI")
 City.create (name: "UTICA")
 City.create (name: "VALDIVIA")
 City.create (name: "VALENCIA")
 City.create (name: "VALLE DE SAN JOSE")
 City.create (name: "VALLE DE SAN JUAN")
 City.create (name: "VALLE DEL GUAMUEZ")
 City.create (name: "VALLEDUPAR")
 City.create (name: "VALPARAISO ANTIOQUIA")
 City.create (name: "VALPARAISO CAQUETA")
 City.create (name: "VEGACHI")
 City.create (name: "VELEZ")
 City.create (name: "VENADILLO")
 City.create (name: "VENECIA ANTIOQUIA")
 City.create (name: "VENECIA CUNDINAMARCA")
 City.create (name: "VENTAQUEMADA")
 City.create (name: "VERGARA")
 City.create (name: "VERSALLES")
 City.create (name: "VETAS")
 City.create (name: "VIANI")
 City.create (name: "VICTORIA")
 City.create (name: "VIGIA DEL FUERTE")
 City.create (name: "VIJES")
 City.create (name: "VILLA CARO")
 City.create (name: "VILLA DE LEYVA")
 City.create (name: "VILLA DE SAN DIEGO DE UBATE")
 City.create (name: "VILLA DEL ROSARIO")
 City.create (name: "VILLA RICA CAUCA")
 City.create (name: "VILLAGARZON")
 City.create (name: "VILLAGOMEZ")
 City.create (name: "VILLAHERMOSA")
 City.create (name: "VILLAMARIA")
 City.create (name: "VILLANUEVA BOLIVAR")
 City.create (name: "VILLANUEVA CASANARE")
 City.create (name: "VILLANUEVA LA GUAJIRA")
 City.create (name: "VILLANUEVA SANTANDER")
 City.create (name: "VILLAPINZON")
 City.create (name: "VILLARRICA")
 City.create (name: "VILLAVICENCIO")
 City.create (name: "VILLAVIEJA")
 City.create (name: "VILLETA")
 City.create (name: "VIOTA")
 City.create (name: "VIRACACHA")
 City.create (name: "VISTAHERMOSA")
 City.create (name: "VITERBO")
 City.create (name: "YACOPI")
 City.create (name: "YACUANQUER")
 City.create (name: "YAGUARA")
 City.create (name: "YALI")
 City.create (name: "YARUMAL")
 City.create (name: "YAVARATE")
 City.create (name: "YOLOMBO")
 City.create (name: "YONDO")
 City.create (name: "YOPAL")
 City.create (name: "YOTOCO")
 City.create (name: "YUMBO")
 City.create (name: "ZAMBRANO")
 City.create (name: "ZAPATOCA")
 City.create (name: "ZARAGOZA")
 City.create (name: "ZARZAL")
 City.create (name: "ZETAQUIRA")
 City.create (name: "ZIPACON")
 City.create (name: "ZIPAQUIRA")

 Area.create (name: "INGENIERÍA, ARQUITECTURA, URBANISMO Y AFINES")
 Area.create (name: "BELLAS ARTES")

 Career.create (name: "Ingeniería de Sistemas, Telemática y Afines", area_id: 1)
 Career.create (name: "Diseño", area_id: 2)

 Profiles.create(name: "Administración de Sistemas de Información", career_id: 1)
 Profiles.create(name: "Desarrollador Web", career_id: 1)
 Profiles.create(name: "Análisis, diseño e implementación de sistemas de información", career_id: 1)
 Profiles.create(name: "Administración de bases de datos", career_id: 1)
 Profiles.create(name: "Diseño, construcción y mantenimiento de sitios Web", career_id: 1)
 Profiles.create(name: "Modelamiento de sistemas organizacionales", career_id: 1)
 Profiles.create(name: "Área de comunicaciones", career_id: 1)
 Profiles.create(name: "Seguridad computacional", career_id: 1)
 Profiles.create(name: "Administración de redes", career_id: 1)
 Profiles.create(name: "Diseño e implementación de soluciones telemáticas", career_id: 1)
 Profiles.create(name: "Área de gestión tecnológica", career_id: 1)
 Profiles.create(name: "Evaluación y aplicación de tecnologías de hardware y software en las organizaciones", career_id: 1)
 Profiles.create(name: "Creación de empresas de manejo computarizado de información y de las actividades que de él se deriven", career_id: 1)
 Profiles.create(name: "Administración de sistemas de información", career_id: 1)
 Profiles.create(name: "Área de investigación aplicada a proyectos informáticos", career_id: 1)

Profiles.create(name: "Gráfico", career_id: 2)
Profiles.create(name:"Crear proyectos de comunicación visual, utilizando la imagen como el recurso de más alto poder comunicativo y estético.", career_id: 2)
Profiles.create(name:"Participar en procesos de investigación, conceptualización y desarrollo de proyectos creativos que aborden problemáticas de la comunicación gráfica.", career_id: 2)
Profiles.create(name:"Crear proyectos audiovisuales, electrónicos e interactivos, por medio de aplicaciones informáticas, aplicables a soluciones comunicacionales tales como video, multimedia, web, cine y televisión.", career_id: 2)
Profiles.create(name:"Diseñar y diagramar información, entre ellos gráficas, textos, imágenes, ilustraciones en diferentes medios editoriales como libros, revistas, periódicos y demás publicaciones en medios impresos o electrónicos.", career_id: 2)
Profiles.create(name:"Diseñar proyectos de identidad visual, que impliquen la creación de la imagen de productos y servicios tangibles o intangibles, con distintivos significables en sus procesos de comunicación.", career_id: 2)
Profiles.create(name:"Diseñar, planear y coordinar campañas y piezas publicitarias en diferentes medios, muestras o exhibiciones y espacios comerciales.", career_id: 2)
Profiles.create(name:"Participar en la formulación y desarrollo de proyectos de investigación relacionados con la historia y teoría de la imagen y la comunicación o el desarrollo de proyectos experimentales de creación gráfica y visual.", career_id: 2)
Profiles.create(name:"Crear sistemas de orientación a través de la construcción de piezas informativas e infográficas que logren generar hábitos en el manejo, desplazamiento  y uso de los diferentes espacios.", career_id: 2)
Profiles.create(name:"Mantener una actitud de compromiso y responsabilidad social en el ejercicio de la profesión y dentro de equipos de trabajo multidisciplinario, para contribuir al desarrollo de la cultura visual de la sociedad.", career_id: 2)



 

 

